project:
  type: website
  output-dir: _site

website:
  title: "SIAFI Data Science and Machine Learning Handbook 2026-1"
  navbar:
    left:
      - text: "Introduction to Data Science"
        menu:
          - file: IDS/1_1_fundamentals.ipynb
            text: "Fundamentals"
          - file: IDS/1_3_end_to_end_ml_project.ipynb
            text: "End to End Machine Learning Project"
          - file: IDS/1_4_dimensionality_reduction.ipynb
            text: "Dimensionality Reduction"
      - text: "Machine Learning"
        menu:
          - file: ML/2_1_intro.qmd
            text: "Introduction to Machine Learning"
          - file: ML/2_2_slf.qmd
            text: "Supervised Learning Fundamentals"
          - file: ML/2_3_classification.ipynb
            text: "Classification Fundamentals"
          - file: ML/2_3_2_classification_algorithms.ipynb
            text: "Classification Algorithms"
          - file: ML/2_4_regression.ipynb
            text: "Regression"
          - file: ML/2_5_decision_trees.ipynb
            text: "Decision Trees and Random Forests"
          - file: ML/2_6_unsupervised_learning.ipynb
            text: "Unsupervised Learning"
      - text: "Deep Learning"
        menu:
          - file: DL/3_1_fundamentals.ipynb
            text: "Fundamentals"
          - file: DL/3_2_ann.ipynb
            text: "Artificial Neurons and the Perceptron"
          - file: DL/3_3_pytorch.ipynb
            text: "Building Neural Networks with PyTorch"

format:
  html:
    theme: zephyr
    toc: true
    code-fold: false
  
